version: '3.9'

services:
  # load-balancer:
    # container_name: nginx
    # build: load-balancer/
    # ports: 
      # - "443:443"
    # networks:
      # - frontend
    # restart: unless-stopped
    # depends_on:
      # - app

  app:
    container_name: app
    build:
      context: app/
      target: dev
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    restart: unless-stopped
    # depends_on:
      # - engine
      # - postgres

  # engine:
    # container_name: engine
    # build:
      # context: engine/
      # target: dev
    # expose:
      # - "5000"
    # networks:
      # - backend
    # restart: unless-stopped

  postgres:
    container_name: postgres
    build: postgres/
    expose:
      - "5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/pgsql/data
    restart: unless-stopped
    env_file:
      - app/backend/.env


volumes:
  postgres_data:


networks:
  frontend:
  backend:
