version: '3.9'

services:
  app:
    container_name: app
    build:
      context: app/
      target: production
    ports:
      - "80:3000"
    networks:
      - frontend
      - backend
    restart: unless-stopped
    volumes: 
      - ./app/frontend/src/:/usr/app/frontend/src
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    build: postgres/
    expose:
      - "5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/pgsql/data
    restart: unless-stopped
    env_file:
      - app/backend/.env

volumes:
  postgres_data:

networks:
  frontend:
  backend:
