services:
  # load-balancer:
  # container_name: nginx
  # build: load-balancer/
  # ports:
  # - "443:443"
  # networks:
  # - frontend
  # restart: unless-stopped
  # depends_on:
  # - app

  app:
    container_name: app
    build:
      context: app/
      target: production
    ports:
      - '80:3000'
    networks:
      - frontend
      - backend
    restart: always
    depends_on:
      - postgres
      # - engine

  # engine:
  # container_name: engine
  # build:
  # context: engine/
  # target: dev
  # expose:
  # - "5000"
  # networks:
  # - backend
  # restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - app/backend/.env
    networks:
      - backend
    restart: always

  # test-db:
  # image: postgres:13
  # ports:
  # - 5435:5432
  # env_file:
  # - ./.env.test
  # networks:
  # - backend

volumes:
  postgres_data:

networks:
  frontend:
  backend:
