services:
  # load-balancer:
  # container_name: nginx
  # build: load-balancer/
  # ports:
  # - "443:443"
  # networks:
  # - frontend
  # restart: unless-stopped
  # depends_on:
  # - app

  app:
    container_name: app
    build:
      context: app/
      target: production
    ports:
      - '80:3000'
    networks:
      - frontend
      - backend
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    build: postgres/
    ports:
      - "5432:5432"
    env_file:
      - app/backend/.env
    networks:
      - backend
    restart: always


volumes:
  postgres_data:


networks:
  frontend:
  backend:
