version: '3.9'

services:
  frontend:
    container_name: frontend
    build: frontend/
    ports:
      - "443:443"
    volumes:
      - frontend_data:/etc/config
    networks:
      - frontend
    restart: unless-stopped
    env_file:
      - .env/frontend.env

  backend:
    container_name: backend
    build: backend/
    expose:
      - "9000"
    volumes:
      - backend_data:/etc/config
    depends_on:
      - postgres
    networks:
      - frontend
      - backend
    restart: unless-stopped
    env_file:
      - .env/backend.env

  engine:
    container_name: engine
    build: engine/
    ports: # should be expose
      - "6969:6969"
    # depends_on:
      # - serviceName
    networks:
      - frontend
      - backend
    restart: unless-stopped
    env_file:
      - .env/engine.env

  postgres:
    container_name: postgres
    build: postgres/
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/data
    networks:
      - backend
    restart: unless-stopped
    env_file:
      - .env/postgres.env


volumes:
  frontend_data:
  backend_data:
  postgres_data:


networks:
  frontend:
  backend:
