version: '3.9'

services:
  frontend:
    container_name: frontend
    build: frontend/
    ports:
      - "443:443"
    networks:
      - frontend
    volumes:
      - type: bind
        source: ./frontend/src
        target: /usr/app/src
        read_only: true
    restart: unless-stopped
    # depends_on:
      # - serviceName
    env_file:
      - .env/frontend.env

  backend:
    container_name: backend
    build: backend/
    expose:
      - "9000"
    networks:
      - frontend
      - backend
    volumes:
      - type: bind
        source: ./backend/src
        target: /usr/app/src
        read_only: true
    restart: unless-stopped
    # depends_on:
      # - postgres
    env_file:
      - .env/backend.env

  engine:
    container_name: engine
    build: engine/
    ports: # should be expose
      - "6969:6969"
    networks:
      - frontend
      - backend
    volumes:
      - type: bind
        source: ./engine/src
        target: /usr/app/src
        read_only: true
    restart: unless-stopped
    # depends_on:
      # - serviceName
    env_file:
      - .env/engine.env

  postgres:
    container_name: postgres
    build: postgres/
    expose:
      - "5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/data
    restart: unless-stopped
    # depends_on:
      # - serviceName
    env_file:
      - .env/postgres.env


volumes:
  frontend_data:
  backend_data:
  postgres_data:


networks:
  frontend:
  backend:
