# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          yarn global add eslint@8.10.0

      - name: Run ESLint backend
        run: |
          cd app/backend
          yarn add @typescript-eslint/eslint-plugin
          yarn lint

      - name: Run ESLint frontend
        run: |
          cd ../frontend
          yarn add @typescript-eslint/eslint-plugin
          yarn lint
